name = "pixivnow"
main = "src/worker.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "pixiv-now-cf-prod"
routes = [
  { pattern = "pixiv-now.lukelzlz.workers.dev/*", zone_name = "lukelzlz.top" }
]

[build]
command = "npm run build:worker"
cwd = "."

[[analytics_engine_datasets]]
binding = "ANALYTICS"

[env.production.analytics_engine_datasets]
binding = "ANALYTICS"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
